import './globals.css'
import type { Metadata } from 'next'

import { TRPCProvider } from '@/app/_trpc/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <TRPCProvider>
        <body>{children}</body>
      </TRPCProvider>
    </html>
  )
}
